### ISSUE TITLE
Problem with encoded caret paths in Turtle configs

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedSoftwareDependencies/Components.js#43]
#### Issue type:

- :bug: Bug 

____
#### Description:

I am trying to create a Turtle configuration. It starts as follows:

```turtle
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix css: <https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/>.
@prefix config: <https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/%5E0.0.0/config/presets/>.
@prefix config-ldp: <https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/%5E0.0.0/config/presets/ldp/>.
@prefix config-backend: <https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/%5E0.0.0/config/presets/backend/>.

<> rdfs:seeAlso
    config:acl.json.
```

Note the usage of `%5E` rather than `^`, which is not a valid URI character and needs to be escaped.

This crashes with:

```
Error: Error while parsing file "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/%5e0.0.0/config/presets/acl.json": Unexpected "E" at position 0 in state STOP
```

____
#### Environment:

latest on macOS

#### Crash log:

```
Error: Error while parsing file "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/%5e0.0.0/config/presets/acl.json": Unexpected "E" at position 0 in state STOP
    at Function.addPathToError (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/componentsjs/lib/rdf/RdfParser.js:69:16)
    at PassThrough.<anonymous> (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/componentsjs/lib/rdf/RdfParser.js:42:38)
    at PassThrough.emit (events.js:327:22)
    at JsonLdParser.<anonymous> (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/componentsjs/node_modules/rdf-parse/lib/RdfParser.js:71:47)
    at JsonLdParser.emit (events.js:327:22)
    at Parser.jsonParser.onError (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:370:18)
    at Parser.proto.charError (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/jsonparse/jsonparse.js:90:8)
    at Parser.proto.write (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/jsonparse/jsonparse.js:154:23)
    at JsonLdParser._transform (/Users/ruben/Documents/UGent/Solid/solid-community-server/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:110:25)
    at JsonLdParser.Transform._read (_stream_transform.js:191:10)
```

**Comment by rubensworks** [comment]
Probably part of a more general issue where we need to handle escaped characters before following import/seeAlso links. Because this can also occur in JSON-LD (and other formats)

Another issue I see here is that error reporting should be improved when dereferencing fails.

**Comment by rubensworks** [comment]
Will be included in 5.x.
